name: mental_arithmetic
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.14
  freezed_annotation: ^2.2.0
  freezed: ^2.5.7
  flutter_bloc: ^8.1.6
  google_fonts: ^6.2.1
  vibration: ^2.0.1
  cupertino_icons: ^1.0.8
  auto_size_text: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.13
  device_preview: ^1.2.0
  flutter_phoenix: ^1.1.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/logo/
